variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  TFPLAN: $CI_COMMIT_REF_SLUG.tfplan
  TFSTATE: $CI_COMMIT_REF_SLUG.tfstate

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .terraform

stages:
  - init
  - plan
  - deploy

before_script:
  - terraform --version
  - terraform init plans

plan:validate:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - terraform validate plans
  only:
    refs:
      - merge_request
      - master

plan:tf:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - terraform plan -no-color -state=$TFSTATE -out=$TFPLAN plans
  only:
    refs:
      - merge_request
      - master
  artifacts:
    name: plan
    paths:
      - $TFPLAN
      - $TFSTATE

deploy:tf:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - terraform apply -state=$TFSTATE -auto-approve -refresh=true -input=false $TFPLAN
  when: manual
  only:
    refs:
      - master
  dependencies: 
    - plan:tf

deploy:s3:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - aws --version
    - make publish
  only:
    refs:
      - master
