before_script:
  - terraform --version
  - aws --version

stages:
  - plan
  - deploy

plan:
  retry: 2
  tags:
    - terraform
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - master

deploy:
  retry: 2
  tags:
    - terraform
  stage: deploy
  script:
    - make deploy
  only:
    refs:
      - master
