before_script:
  - python3 --version
  - pylint --version
  - aws --version

stages:
  - test
  - build
  - deploy

lint:
  retry: 2
  tags:
    - python
  stage: test
  script:
    - echo ok
  only:
    refs:
      - merge_request

build-artifacts:
  retry: 2
  tags:
    - python
  stage: build
  script:
    - echo ok
  only:
    refs:
      - master

deploy:
  tags:
    - python
  stage: deploy
  script:
    - echo ok
  only:
    refs:
      - master
