variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

before_script:
  - terraform --version
  - aws --version

stages:
  - plan
  - deploy

plan:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - master
  artifacts:
    paths:
    - build/.tfplan

deploy:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - make deploy
  only:
    refs:
      - master
  dependencies: 
    - plan