variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

before_script:
  - terraform --version
  - aws --version

stages:
  - init
  - plan
  - deploy

init:tf:
  retry: 2
  tags:
    - python
  stage: init
  script:
    - make init
  only:
    refs:
      - merge_request
      - master
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .terraform

plan:validate:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make validate
  only:
    refs:
      - merge_request
      - master
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .terraform

plan:tf:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - master
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .terraform
  artifacts:
    name: plan
    paths:
      - build/.tfplan

deploy:tf:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - make deploy
  when: manual
  only:
    refs:
      - master
  dependencies: 
    - plan:tf
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .terraform

deploy:s3:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - make publish
  only:
    refs:
      - master
