variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

before_script:
  - terraform --version
  - aws --version

stages:
  - plan
  - deploy

cache:
  key: terraform-state
  paths:
    - .terraform

init:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make init
  only:
    refs:
      - merge_request
      - master

validate:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make validate
  only:
    refs:
      - merge_request
      - master

plan:
  retry: 2
  tags:
    - python
  stage: plan
  script:
    - make plan
  only:
    refs:
      - merge_request
      - master
  artifacts:
    name: plan
    paths:
      - build/.tfplan

deploy:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - make deploy
  when: manual
  only:
    refs:
      - master
  dependencies: 
    - plan

publish:
  retry: 2
  tags:
    - python
  stage: deploy
  script:
    - make publish
  only:
    refs:
      - master
